# Generated by Django 5.2.1 on 2025-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=250, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=250, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
