# Generated by Django 5.2.1 on 2025-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
